apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-exporter.fullname" . }}
  labels:
    scrape-service-metrics: "true"
    {{- include "helm-exporter.labels" . | nindent 4 }}
  {{- if not .Values.serviceMonitor.create }}
  annotations:
    prometheus.io/scrape: "true"
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "helm-exporter.selectorLabels" . | nindent 4 }}
